name: Secret Scanning (Gitleaks)

on:
  pull_request:
    branches:
      - main
      - develop
    types:
      - closed

permissions:
  contents: read
  pull-requests: read

jobs:
  gitleaks:
    name: Gitleaks Secret Scan
    if: github.event_name == 'workflow_dispatch' || github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    timeout-minutes: 20

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: false
      - name: Run Gitleaks CLI (Free for Enterprise)
        run: |
          docker run --rm -v ${{ github.workspace }}:/path zricethezav/gitleaks:latest detect --source="/path" --verbose

